//! HLS playlist + segment file server for the ffmpeg pipes.

use axum::{
    body::Body, extract::State as AxumState,
    http::{HeaderMap, HeaderValue, StatusCode},
    response::{IntoResponse, Response},
};

use crate::StreamState;


/// Serve HLS playlist (.m3u8) and segment (.ts) files generated by ffmpeg.
/// Requires CORS headers so the browser's HLS player can load cross-origin.
pub(crate) async fn hls_serve(
    axum::extract::Path(file): axum::extract::Path<String>,
    AxumState(s): AxumState<StreamState>,
) -> Response {
    // Validate: only alphanumeric, dash, underscore, dot
    if !file.chars().all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.')) {
        return StatusCode::FORBIDDEN.into_response();
    }
    let path = s.data_dir.join("hls").join(&file);
    let data = match tokio::fs::read(&path).await {
        Ok(d) => d,
        Err(_) => return StatusCode::NOT_FOUND.into_response(),
    };
    let ct = if file.ends_with(".m3u8") { "application/vnd.apple.mpegurl" }
             else if file.ends_with(".ts") { "video/MP2T" }
             else { "application/octet-stream" };
    let mut headers = HeaderMap::new();
    headers.insert("Content-Type",  HeaderValue::from_str(ct).unwrap());
    headers.insert("Cache-Control", HeaderValue::from_static("no-cache"));
    headers.insert("Access-Control-Allow-Origin", HeaderValue::from_static("*"));
    (StatusCode::OK, headers, Body::from(data)).into_response()
}

// ─── ONNX Runtime inference engine ────────────────────────────────────────────
//
// Runs YOLO26x (onnx-community/yolo26x-ONNX) via ORT (Microsoft ONNX Runtime, CPU).
// Model is loaded from <data_dir>/skills/yolo26/model.onnx — only when the
// YOLO26 skill is installed by the user via Agent → Skills.
// Frames arrive via watch channel (process_frame writes, inference loop reads).
// No frame data crosses the IPC bridge for AI — only the JSON result does.

